const QUESTIONS = [
    { id: 1, text: "When a crisis happens, what is your first instinct?", answers: [{ text: "Slow everything down and understand the situation.", traits: { intelligence: 3, control: 3, patience: 2 }}, { text: "Take charge immediately.", traits: { leadership: 3, courage: 3, confidence: 2 }}, { text: "Protect the people around me first.", traits: { empathy: 3, justice: 2, resilience: 1 }}, { text: "Adapt and improvise.", traits: { adaptability: 3, creativity: 2, risk: 2 }}] },
    { id: 2, text: "What motivates you most?", answers: [{ text: "Knowledge", traits: { curiosity: 3, intelligence: 3 }}, { text: "Power", traits: { ambition: 3, confidence: 2 }}, { text: "Freedom", traits: { independence: 3, adaptability: 2 }}, { text: "Helping others", traits: { empathy: 3, justice: 3 }}] },
    { id: 3, text: "How do people usually describe you?", answers: [{ text: "Calm", traits: { control: 3, patience: 2 }}, { text: "Creative", traits: { creativity: 3, innovation: 3 }}, { text: "Fearless", traits: { courage: 3, risk: 3 }}, { text: "Reliable", traits: { discipline: 3, resilience: 2 }}] },
    { id: 4, text: "You find a locked door in an abandoned facility. Do you:", answers: [{ text: "Pick the lock to see what’s inside.", traits: { curiosity: 3, risk: 2 }}, { text: "Find another way; breaking and entering is inefficient.", traits: { intelligence: 3, discipline: 2 }}, { text: "Assume it’s locked for a reason and move on.", traits: { control: 3, patience: 2 }}, { text: "Force it open.", traits: { confidence: 3, courage: 2 }}] },
    { id: 5, text: "A peer fails to meet a critical deadline. Your reaction:", answers: [{ text: "Identify the bottleneck and streamline their process.", traits: { leadership: 3, intelligence: 2 }}, { text: "Cover for them; we succeed or fail as a team.", traits: { empathy: 3, justice: 2 }}, { text: "Hold them accountable; standards must be maintained.", traits: { discipline: 3, control: 2 }}, { text: "Assume they had a reason and offer to help.", traits: { empathy: 3, patience: 2 }}] },
    { id: 6, text: "How do you handle emotional pressure?", answers: [{ text: "I compartmentalize and focus on the objective.", traits: { control: 3, resilience: 3 }}, { text: "I channel it into a creative output.", traits: { creativity: 3, innovation: 2 }}, { text: "I acknowledge it and use it to drive me.", traits: { ambition: 3, courage: 2 }}, { text: "I disconnect entirely to regain perspective.", traits: { independence: 3, patience: 2 }}] },
    { id: 7, text: "You are offered a massive reward for a task that feels morally grey. Do you:", answers: [{ text: "Refuse. The cost to my integrity is too high.", traits: { justice: 3, discipline: 3 }}, { text: "Accept. In the grand scheme, the ends justify the means.", traits: { ambition: 3, risk: 2 }}, { text: "Negotiate. I want to know exactly what I am signing up for.", traits: { intelligence: 3, independence: 2 }}, { text: "Accept, but leave a backdoor to minimize collateral damage.", traits: { creativity: 3, justice: 1 }}] },
    { id: 8, text: "What environment do you perform best in?", answers: [{ text: "Strict, orderly, and highly regulated.", traits: { control: 3, discipline: 3 }}, { text: "Fast-paced, unpredictable, and chaotic.", traits: { chaos: 3, adaptability: 3 }}, { text: "Collaborative, open, and idea-driven.", traits: { empathy: 3, creativity: 2 }}, { text: "Solitary, quiet, and introspective.", traits: { independence: 3, intelligence: 2 }}] },
    { id: 9, text: "If you could change one thing about human nature, what would it be?", answers: [{ text: "Eliminate irrational fear.", traits: { courage: 3, intelligence: 2 }}, { text: "Increase capacity for deep compassion.", traits: { empathy: 3, justice: 2 }}, { text: "Amplify the drive for constant progress.", traits: { ambition: 3, innovation: 3 }}, { text: "Balance the desire for control with the need for spontaneity.", traits: { adaptability: 3, control: 2 }}] },
    { id: 10, text: "How do you define 'success'?", answers: [{ text: "Achieving a goal that leaves a permanent mark.", traits: { ambition: 3, innovation: 2 }}, { text: "Maintaining inner peace and stability.", traits: { control: 3, patience: 3 }}, { text: "Improving the lives of those around me.", traits: { justice: 3, empathy: 3 }}, { text: "Continuous learning and self-evolution.", traits: { curiosity: 3, adaptability: 2 }}] },
    { id: 11, text: "A long-held belief of yours is proven wrong. Your reaction:", answers: [{ text: "Relief. Now I can build a better map of reality.", traits: { intelligence: 3, innovation: 3 }}, { text: "Skepticism. I need to verify the source.", traits: { intelligence: 3, discipline: 2 }}, { text: "Adaptation. I update my view and move on.", traits: { adaptability: 3, resilience: 2 }}, { text: "Defiance. I stick to my gut, even if evidence says otherwise.", traits: { independence: 3, confidence: 2 }}] },
    { id: 12, text: "You are the last person on earth for 24 hours. What do you do?", answers: [{ text: "Read, study, and observe everything without interference.", traits: { curiosity: 3, intelligence: 2 }}, { text: "Build something massive or test my limits.", traits: { innovation: 3, ambition: 2 }}, { text: "Reflect and recharge.", traits: { patience: 3, resilience: 2 }}, { text: "Break every rule I usually follow.", traits: { chaos: 3, risk: 3 }}] },
    { id: 13, text: "How do you approach conflict?", answers: [{ text: "Tactically. I outmaneuver before a blow is ever struck.", traits: { intelligence: 3, control: 3 }}, { text: "Directly. I meet it head-on to end it quickly.", traits: { courage: 3, confidence: 3 }}, { text: "Diplomatically. I seek common ground.", traits: { empathy: 3, patience: 2 }}, { text: "I ignore it until it resolves itself or becomes critical.", traits: { chaos: 2, adaptability: 2 }}] },
    { id: 14, text: "You have the chance to automate a job held by someone you know. Do you?", answers: [{ text: "Yes, efficiency is the only path to progress.", traits: { intelligence: 3, ambition: 3 }}, { text: "No, the human element is irreplaceable.", traits: { empathy: 3, justice: 2 }}, { text: "Yes, but I’ll re-skill them for a better position.", traits: { leadership: 3, innovation: 2 }}, { text: "I'll optimize it, but let them decide the transition.", traits: { adaptability: 3, patience: 2 }}] },
    { id: 15, text: "When you see a broken system, do you:", answers: [{ text: "Fix it immediately to stop the bleed.", traits: { discipline: 3, courage: 2 }}, { text: "Study it to ensure the replacement is perfect.", traits: { intelligence: 3, control: 3 }}, { text: "Burn it down and start from scratch.", traits: { chaos: 3, risk: 3 }}, { text: "Wait for the right moment to pivot.", traits: { patience: 3, adaptability: 2 }}] }
];